name: Build Template
on: push

jobs:
    build-template:
        name: Build Mustache template
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9.2"

            - name: Install pipenv
              run: pip install pipenv

            - name: Install dependencies
              run: pipenv install

            - name: Render Mustache template
              run: pipenv run python3 build.py

            - name: Set user details
              run: |
                  git config user.email "11467778+leoriviera@users.noreply.github.com"
                  git config user.name "Leo Riviera"

            - name: Stage changed files
              run: git add .

            - name: Commit changed files
              run: git commit -m "Update index.html"

            - name: Push code to master
              run: git push origin HEAD:master
